### ISSUE TITLE
Problem installing packages on Ubuntu

### ISSUE THREAD

**Issue by seamusomurchu** [andrewcparnell/Rfternoon#1]
I hope this is the right location to ask questions. I am using Ubuntu 16.04. When I installed R I got an old version of R (3.2.3).

I tried updated R and installed r-base-dev and still not look installing the rstan package

> install.packages(c('rstan'))
Installing package into ‘/home/james/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘rstan’ is not available (for R version 3.2.3)

There seems to be a similar problem with the mlr package 
Cannot find xml2-config
ERROR: configuration failed for package ‘XML’
* removing ‘/home/james/R/x86_64-pc-linux-gnu-library/3.2/XML’
Warning in install.packages :
  installation of package ‘XML’ had non-zero exit status
ERROR: dependencies ‘ParamHelpers’, ‘XML’ are not available for package ‘mlr’
* removing ‘/home/james/R/x86_64-pc-linux-gnu-library/3.2/mlr’
Warning in install.packages :
  installation of package ‘mlr’ had non-zero exit status

Kind regards,
James

**Comment by andrewcparnell** [comment]
Hi James,

try following this page [here](https://cran.r-project.org/bin/linux/ubuntu/README.html). R 3.2.3 is very old (December 2015!) and this will get you the latest version. 

Andrew

**Comment by seamusomurchu** [comment]
Does it matter which of these I choose;

To obtain the latest R 4.0 packages, add an entry like

deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/

or

deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/

or

deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran40/

James

**Comment by andrewcparnell** [comment]
I think if you look up Ubuntu 16.04 that's Xenial Xerus so I'd go with the xenial one.

**Comment by seamusomurchu** [comment]
Got R version 4, installing the packages now, thanks!

**Comment by andrewcparnell** [comment]
Brilliant. Keep me posted if you get stuck. If `rstan` causes problems (which hopefully it won't) leave it for now and work through the other videos.
